name: Build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: latest

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Point MSBuild to vendored .NET 4.0 refs
        shell: powershell
        run: |
          $ref = [System.IO.Path]::Combine($env:GITHUB_WORKSPACE, 'third_party', 'Microsoft.NETFramework.ReferenceAssemblies.net40', 'build', '.NETFramework', 'v4.0')
          if (-not (Test-Path $ref)) { throw "Missing vendored v4.0 ref assemblies at $ref" }
          "FrameworkPathOverride=$ref" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore packages
        run: nuget restore Moto_Logo.sln

      - name: Build Release
        run: msbuild Moto_Logo.sln /t:Build /p:Platform=x64 /p:Configuration=Release /m

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MotoBootLogoMaker-Release
          path: |
            **/bin/Release/**
          if-no-files-found: error
