name: Build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: latest

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # Install .NET Framework 4.0 Targeting Pack (Developer Pack) so MSBuild can find v4.0 reference assemblies
      - name: Install .NET Framework 4.0 Targeting Pack
        shell: powershell
        run: |
          choco install -y netfx-4.0.3-devpack

      - name: Restore packages
        run: nuget restore Moto_Logo.sln

      - name: Build Release
        run: msbuild Moto_Logo.sln /t:Build /p:Configuration=Release /m

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MotoBootLogoMaker-Release
          path: |
            **/bin/Release/**
          if-no-files-found: error
